llm:
  model: gpt-3.5-turbo
  temperature: 0.8
style:
  joke_rate: 0.2
  vague_rate: 0.1
intervention:
  enabled: true
  base_prob: 0.02
  silence_threshold: 5
  interval_minutes: 60
  channels:
    - "1353687394401910797"
    - "1364622450918424576"
  active_hours:
    start: 8
    end: 23
memory:
  match_threshold: 0.7
bot:
  ignoreBots: false
  trigger_words:
    - がっこ
    - がっこちゃん
    - がっ子
    - がっ子ちゃん
  bot_loop_limit: 3
  bot_loop_reset_minutes: 60
etl:
  export_path: ./data/logs
  schedule: "0 18 * * *" 