members:
  - id: "1234567890"
    username: sample_user
    callname: サンプル
    tags: ["AI", "教育", "プログラミング"]
  - id: "0987654321"
    username: another_user
    callname: テスト 
    tags: ["音楽", "旅行", "映画"] 